### ISSUE TITLE
Close cooling valves when the water alarm is triggered

### ISSUE THREAD

**Issue by ZishuoYang** [umd-lhcb/NeoBurnIn#11]
@yipengsun We want to update the configuration such that cooling valves are closed when the water alarm is triggered. I was going to do so by repeating this for relay1 ch1. What do you think? 

https://github.com/umd-lhcb/NeoBurnIn/blob/2b1394b0609e82682ebaf1b95fc27ce5e841dab5/measurements/test_temp_ctrl_client.yml#L89-L94

Although, this could be overwritten if another condition is met first:
https://github.com/umd-lhcb/NeoBurnIn/blob/2b1394b0609e82682ebaf1b95fc27ce5e841dab5/measurements/test_temp_ctrl_client.yml#L62-L68

**Comment by yipengsun** [comment]
> if another condition is met first

Note that for every measurement received, **ALL** rules will **ALWAYS** be looped over trying to find a match. So even if another condition is met first, the loop will continue, and if it finds another match, then the action will be executed as well.

In other words, the ordering of the rules doesn't really matter: It only affects the execution order of the actions.

**Comment by ZishuoYang** [comment]
> > if another condition is met first
> 
> Note that for every measurement received, **ALL** rules will **ALWAYS** be looped over trying to find a match. So even if another condition is met first, the loop will continue, and if it finds another match, then the action will be executed as well.
> 
> In other words, the ordering of the rules doesn't really matter: It only affects the execution order of the actions.

It's not the ordering I worry about, but that our TimeOut can block the USB relay operation we want (to turn off).

**Comment by yipengsun** [comment]
Let's set timeout to 0 then. See if USB relay control is unhappy about it. Our thermistor polling rate is 5 seconds, so I guess even if we try to turn on USB relay repeatedly, it will be fine (?)

**Comment by yipengsun** [comment]
The valve on/off thresholds need more tuning, but the functionality is there. Closed for now.
