### ISSUE TITLE
Water alarm falsely triggered right after Maraton control commands

### ISSUE THREAD

**Issue by ZishuoYang** [umd-lhcb/NeoBurnIn#14]
After having Maraton channels 1,2,12 on for DCB testing, I started to turn them off with the curl command. 

After I entered the command the turn off channel 1 (`curl -X POST http://192.168.1.30:45679/psu/192.168.1.31/1/off`), I noticed that **all three channels** were turned off at the same time.

Not sure of what I saw, I immediately issued the second command to turn all channels off (`curl -X POST http://192.168.1.30:45679/psu/192.168.1.31/all/off`). At this point, I saw the water alarm message (most likely just appeared) on the screen.  

I confirm that no water was on the sensor.

**Comment by yipengsun** [comment]
This might be just a fluke on the pi's GPIO, because Maraton control doesn't touch on GPIO.

**Comment by ZishuoYang** [comment]
It's most likely a fluke, given that this didn't happen for O(100) maraton operations I have done. I will double check the electrical connections to the water alarm. There are some places where insulation can be improved.

**Comment by yipengsun** [comment]
Closed for now. If something similar happens again, we'll reopen the investigation.
