### ISSUE TITLE
pi crashes after a couple of hours

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/NeoBurnIn#15]
## Sympton
pi crashes after a couple of hours, and the same problem was happening back in Feb. Here's Zishuo's photos taken when the pi was in a dead state:
![Image from iOS (1)](https://user-images.githubusercontent.com/33738176/86277792-e7542380-bc09-11ea-9e48-3171ccf4c664.jpg)
![Image from iOS](https://user-images.githubusercontent.com/33738176/86277799-ea4f1400-bc09-11ea-83f6-60b0680b188a.jpg)

## Plan to debug
- [x] Replace current pi with a new pi
    - Insert SD card to new pi
    - `sudo nixos-rebuild switch`
    - Reboot
    - Check if the IP address on `eth0` is `192.168.1.30` with `ip addr`
    - If not, `sudo systemctl restart dhcpcd`, and try again
    - In worst case scenario, we can't SSH to pi, but pi can still do the testing, and we will still receive warning about pi being inactive if the new pi also dies.

- [ ] Update NixOS
- [x] Run our burn-in software in Raspbian
- [ ] Make the code simpler

**Comment by ZishuoYang** [comment]
Right. The second screenshot was taken this morning. From the time stamps, I believe the error messages about transmission fail happened before Yipeng started running the necessary DataServer script (so those are not related to the crash).

**Comment by yipengsun** [comment]
@ZishuoYang @manuelfs @CoffeeIntoScience I listed possible ways to go forward, FYI.

**Comment by yipengsun** [comment]
@ZishuoYang I've updated instruction on how to move current SD card to a new pi.

**Comment by ZishuoYang** [comment]
Note that yesterday, Yipeng had disabled the Maraton monitoring part of the program,  and I started running it around 9 AM. It's interesting that we didn't see anything wrong for~8 hrs, before keyboard interruption stopped it. So Yipeng thinks it could be due to the Maraton monitoring part of his code.

**Comment by ZishuoYang** [comment]
![image](https://user-images.githubusercontent.com/12600353/86596754-c3297700-bf68-11ea-9500-8fd3953155cb.png)

Since the old Pi crashed again after running for ~1 hr, we decided to swap in the new pi. 

@CoffeeIntoScience found a way to change the MAC address: `sudo ifconfig eth0 hw ether <new MAC addr>` (after ifconfig eth0 down). We can ssh into the new Pi after this.

I labelled and moved all the GPIO connections, and started running the monitoring scripts around 3PM. 

I will test the alarms to confirm that they work.

**Comment by yipengsun** [comment]
The new pi has crashed again. I think now we can conclude that the old pi should be fine. The next step would be to use Raspbian.

**Comment by yipengsun** [comment]
Some manual configuration for the Raspbian is needed, I'll look it up and update the README.

**Comment by yipengsun** [comment]
I've updated the procedure to "install" this project on Raspbian to the README. Please refer to the [installation section](https://github.com/umd-lhcb/NeoBurnIn#installation-on-raspbian).

FYI @ZishuoYang @CoffeeIntoScience @manuelfs.

**Comment by yipengsun** [comment]
Also, if you run into problems, take a picture of the error and upload the picture here, and also ping me on slack.

**Comment by ZishuoYang** [comment]
The new Pi with Raspbian OS is now running (starting from ~2:30PM). I changed the thermal sensor readout interval from 5s to 1s, which may aggravate the potential cause for crash.

**Comment by CoffeeIntoScience** [comment]
The errors from the log:
```
2020-07-06 15:14:38.314 WARNING  Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-06 15:09:31.408913|MARATON_CURR6|0.36328125\n')
2020-07-06 15:20:58.317 WARNING  Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-06 15:15:57.985321|COMBINED_WIRE|21.166666666666668\n')
2020-07-06 15:21:03.318 WARNING  Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-06 15:16:02.786105|COMBINED_WIRE|21.203\n')
2020-07-06 15:23:08.334 WARNING  Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-06 15:18:08.074878|COMBINED_WIRE|21.24975\n')
2020-07-06 15:25:00.316 WARNING  Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-06 15:19:59.825430|COMBINED_WIRE|21.26525\n')
2020-07-06 15:25:09.316 WARNING  Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-06 15:20:09.185956|COMBINED_WIRE|21.26525\n')
2020-07-06 15:28:12.316 WARNING  Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-06 15:23:11.739112|MARATON_CURR12|0.31640625\n')
```

**Comment by CoffeeIntoScience** [comment]
Notably(?) I see *nothing* in `journalctl -m` during this time window, just USB communication with the relay

**Comment by ZishuoYang** [comment]
Here's the screenshot when errors started appearing, and I notices python3 gets 100%CPU every few minutes. 

![image](https://user-images.githubusercontent.com/12600353/86632813-dc98e600-bf9d-11ea-84e5-4dcfaa9d5b59.png)


A couple of minutes before the errors started, I verified the Maraton remote control (the curl commands). Can this be related to the first error in pic about Maraton current data transmission failure?

**Comment by yipengsun** [comment]
I think somehow the 100% CPU usage breaks the IO system of the kernel, making internet connection unavailable and USB relay reconnecting.

Given that:
- Triggering fire alarm causes 100% CPU usage
- We ARE reading the GPIO pin for every 0.1 second
- There really is no fundamental difference between alarm triggered and not

I think the fire alarm code (likely together with water alarm) caused our pi to break.

My predictions:

1. The Raspbian pi will also crash.
2. If you run the fire alarm code only, you will still have 100% CPU usage from time to time.

**Comment by yipengsun** [comment]
However, I think we should let the pi continue to run and see if it actually crashes.

**Comment by yipengsun** [comment]
Later, to run fire alarm code individually:

1. Clone the `rpi.burnin` repo, then go to the project root.
2. `./bin/FireAlarm.py <gpio_ch_number>`

**Comment by yipengsun** [comment]
Also, the `journalctl` maybe is not working because 100% CPU usage might have prevented it from working properly. I personally never see something like this on my laptops, but who knows when we only have a low-performing ARM CPU :-(

**Comment by ZishuoYang** [comment]
I tested the fire alarm code alone with `./bin/FireAlarm.py 8`, and saw 100%CPU. 

I then changed the interval in FireAlarm.py, from 0.1 to 5 (seconds), and still see 100%CPU.

**Comment by ZishuoYang** [comment]
After running continuously for 17+ hours, the Raspbian Pi has not crashed. CPU usage goes to 100% every couple of minutes. The same type of error messages appear every few minutes: 

```
NeoBurnIn.io.client post():132       Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-07 09:36:10.865456|COMBINED_WIRE|21.2185\n')
NeoBurnIn.io.client post():132       Transmission for the following msg failed, with the following exception TimeoutError: bytearray(b'2020-07-07 09:36:37.577947|MARATON_CURR7|0.33203125\n')
```

**Comment by yipengsun** [comment]
Since the pi now works (with some caveats that we can bear for now), I'll close this issue. Will reopen if any bug that disturb our normal burn-in activities occur.
