### ISSUE TITLE
Monitoring and control improvements needed

### ISSUE THREAD

**Issue by ZishuoYang** [umd-lhcb/NeoBurnIn#16]
- [x] update condition when monitoring Maraton current:
  - For channels with constant current (DCB burn-in), 3sigma from past average triggers on fluctuations every few hours. For LVR burn-in channels, the current is supposed to switch between high and low (load-switching), so N sigma from average is not a good condition.

- [x] web monitoring displays only a couple of hours' temperature data. Need more history to help checking for blips. 

- [x] Decide whether to update the thermal cycling profile
  - currently, between 30C and 40C measured (true temp on board ~30C and ~50C)

- [x] investigate the small thermal sensor blips (did not see this before changing readout interval 5s->1s?)

- [ ] try to fix the Maraton control issue mentioned in #12 

![image](https://user-images.githubusercontent.com/12600353/87157108-b61fc700-c28b-11ea-91d4-5e3a3e0436df.png)

**Comment by yipengsun** [comment]
Hmm, the thermistor data is displayed for ~1 hr? I think in the `DataServer.py`, we keep only the most recent 1000 datapoints in memory, and suppose we take 1 dp/sec, then we should be able to see less than 1 hours of data.

Suppose we take 1 dp/5sec, then in an hour we have 3600/5=720 datapoints,  so we can see a the plot of a bit over 1 hr.

Anyway, we can keep more datapoints in the memory, see 10000 datapoints.

**Comment by yipengsun** [comment]
For the 3 std alarm, I don't see a good way to check it now that we are toggling channels. Maybe we can just disable it.

**Comment by yipengsun** [comment]
Any new suggestions for checking the Maraton channels that are responsible for the switch load boards?

I think we need something relatively simple and easy to implement.

If we don't have good ideas, we can disable check completely for these channels.

**Comment by yipengsun** [comment]
I've updated data sources to readout thermistors individually, which can help us debugging the occasional blips.

Also, not sure why the `interval` keyword is not working. There might be a bug and I tried to fix it. Let's see if it works now.

**Comment by yipengsun** [comment]
One thing for sure: This blip is not the old problem where sometimes the thermistor will read `85.0`, because now we have blips in both directions.

**Comment by ZishuoYang** [comment]
> One thing for sure: This blip is not the old problem where sometimes the thermistor will read `85.0`, because now we have blips in both directions.

How are we having blips in both directions? I only saw one spike to ~50 in the first burnin history, and I saw a spike to ~35 today. If one sensor readout is around 85, it would have resulted in similar increase to that in the average.

**Comment by yipengsun** [comment]
The picture you posted at top has blips in both directions.

**Comment by yipengsun** [comment]
If you are talking about THE BLIP at around 50 C: 

1. The thermistor readout code will suppress a single `85.0` readout.
2. If another `85.0` is read immediately after the suppressed `85.0`, then this `85.0` will be read normally
3. Suppose two adjacent readout of 85 C, so we do have a `85.0` readout: 85x1/4 + 40x3/4 ~ 50

Indeed this is possible.

**Comment by ZishuoYang** [comment]
> The picture you posted at top has blips in both directions.

OK I see, you mean the small (~2C) jumps. The large spike (10-15C) is more concerning and what I was thinking about, because it can cut a cycle short on the rising edge.

**Comment by ZishuoYang** [comment]
> Any new suggestions for checking the Maraton channels that are responsible for the switch load boards?
> 
> I think we need something relatively simple and easy to implement.
> 
> If we don't have good ideas, we can disable check completely for these channels.

What about implementing what @manuelfs mentioned last Friday? I think it's necessary to check these channels, not for the monitoring the switching load boards, but for monitoring problem/failure of LVRs.

**Comment by ZishuoYang** [comment]
> 2\. If another `85.0` is read immediately after the suppressed `85.0`, then this `85.0` will be read normally

We should change this to make it more robust then. For example, only read normally after at least 3 consecutive 85.0. 

It's also possible to have a different value, e.g. 90.0. 

We should have a clear idea when the individual sensor logs are working.

**Comment by ZishuoYang** [comment]
I did disconnect and reconnect the +5V wire from Pi to sensor breakout board, in hope of resetting the sensors' states. 

This large jump happened after that:

![image](https://user-images.githubusercontent.com/12600353/87430869-d1ecdb00-c5b3-11ea-9ab2-7d14677419fb.png)


There has been no sudden change larger than 0.5C in the last ~12 hrs while sensors are in room temperature. 

![image](https://user-images.githubusercontent.com/12600353/87430570-66a30900-c5b3-11ea-897b-b5c16631d109.png)

**Comment by yipengsun** [comment]
> > 2. If another `85.0` is read immediately after the suppressed `85.0`, then this `85.0` will be read normally
> 
> We should change this to make it more robust then. For example, only read normally after at least 3 consecutive 85.0.
> 
> It's also possible to have a different value, e.g. 90.0.

Jorge did some tests on this, and it seems that all erroneous reading were `85.0` (according to the spec, the sensor supports up to ~110 C).

But yes, at least we can change to 3 consecutive `85.0` readout.  


> We should have a clear idea when the individual sensor logs are working.

Hmm, the individual readout is indeed not working: I can't see a single readout in the log file. Perhaps when we are not doing the burn-in, we can disable the `COMBINED_WIRE` channel only.

I suspect that the 1-wire protocol doesn't support concurrent readout.

**Comment by ZishuoYang** [comment]
> Hmm, the individual readout is indeed not working: I can't see a single readout in the log file. Perhaps when we are not doing the burn-in, we can disable the `COMBINED_WIRE` channel only.

@yipengsun We are only running 3 Maraton channels for DCB burn-in right now, until tomorrow, so we just need the fire/water alarms running. Feel free to make changes to combined_wire channel or other temperature monitoring to test things. 

> 
> I suspect that the 1-wire protocol doesn't support concurrent readout.

I'm not sure what you mean. The current value we see, COMBINED_WIRE, is simply the mean of all sensor values. So it seems to me that your code has been parsing the files under /sys/bus/w1/devices/... and reading individual values. Doesn't have to be simultaneous, if we just want to see the values every 5s.

**Comment by yipengsun** [comment]
What is the algorithm that Manuel suggested on Friday? I didn't hear him well and still don't understand the idea.

**Comment by yipengsun** [comment]
Also, my claim that _1-wire doesn't handle concurrent readout_ doesn't make sense.

I looked up the kernel documentation of [`w1_therm`](https://www.kernel.org/doc/html/v4.18/driver-api/w1.html), and there's no mentioning of forbidding concurrent reading.

I then did a test:
```
cd /sys/bus/w1/devices/28-0000098d0cbe
cat w1_slave & cat w1_slave
```

So that we try to read again before the first read finishes. Both readout were successful.

I also investigated whether the `crc=<something> YES|NO` is actually useful for preventing erroneous readout, and the result is NO:
```
50 05 4b 46 7f ff 0c 10 1c : crc=1c YES
50 05 4b 46 7f ff 0c 10 1c t=85000
``` 

We have a `85.0` readout, yet the CRC is still correct, so our only way to detect mis-readout is still the `85.0` value.

I think there must be something wrong in the hardware. I plan to add more debug info so that we know what's wrong.

After that, I probably can debug during the weekend, or when you are not burning-in.

**Comment by manuelfs** [comment]
@yipengsun it was not a fully fleshed out algorithm, just an initial idea to perhaps expand on.

To monitor the low and high currents, you could pick the highest and lowest readings for every 60 seconds,  average the highs (and lows separately) over half an hour, and estimate their spreads from those 30 readings as well. Then, you compare new measurements to those two distributions, and check for anomalies.

**Comment by ZishuoYang** [comment]
> I also investigated whether the `crc=<something> YES|NO` is actually useful for preventing erroneous readout, and the result is NO.

> We have a 85.0 readout, yet the CRC is still correct, so our only way to detect mis-readout is still the 85.0 value.

The [1-wire protocol Cyclic Redundancy Check](https://www.maximintegrated.com/en/design/technical-documents/app-notes/2/27.html) is calculated from the rest of the data bytes, to check if data arrived unchanged. But transmission error is not causing `85.0`, according to the [datasheet](https://cdn.sparkfun.com/assets/4/a/8/8/8/DS18B20.pdf):
"The power-on reset value of the temperature register is +85°C."
From online users' discussions (google `DS18B20 85 error`), the temperature sensor has either not received an instruction to do a temperature conversion, or it has not had the time to do a conversion, before read command is issued.  

By `cat w1_slave & cat w1_slave`, it seems likely that sensor had no time to do temperature conversion. So it's a good idea to check if something similar is in your code.  

But checking the CRC will be useful in preventing transmission errors, which could be the cause of our problems.

**Comment by ZishuoYang** [comment]
The large spike happened again last night ~1AM. Note the different magnitude compared to my screenshot above. With similar baseline room temp, the 85C error cannot have produced both blips. 

![image](https://user-images.githubusercontent.com/12600353/87559450-501ab180-c688-11ea-9da7-908ee5a1aa12.png)

**Comment by ZishuoYang** [comment]
The large spike just happened again, cutting one cycle short. Here's the screenshot. The anomaly was only in COMBINED_WIRE, not in other individual sensor readout. Note that the small spikes also only show up in COMBINED_WIRE. Something is not correct in getting and computing the values for it. 

![image](https://user-images.githubusercontent.com/12600353/87702442-6c415000-c767-11ea-9bdb-33241c6a5e78.png)

**Comment by yipengsun** [comment]
I've made a couple of improvements:

1. Now, when you `Ctrl`+`C` either CtrlClient or CtrlServer, all USB relay channels will be automatically turned on.

2. I have implemented the automatic outlier rejection for thermistor. The readout seems to be more reliable now:

    ![COMBINED_WIRE](https://user-images.githubusercontent.com/33738176/87961396-39d97f00-cae8-11ea-906c-6a151be17fa8.png)

    The trade-off now is that the start up is relatively slow, because we need to sample a couple of good thermistor measurements first. The client should write good measurements to log file after the initialization is complete. Don't `Ctrl`+`C` too soon!

3. I have implemented a slightly smarter Maraton channel error detection: 
    ```
    if current > 5:
      assume high current, and see if this measurement is within 3 std of all HIGH current
    else:
      assume low current, and handle it the same.
    ```
4. I've investigated the high CPU usage of the fire alarm, and couldn't figure out why. Incidentally, I've fixed the high CPU usage for the sample fire alarm scripts.

**Comment by yipengsun** [comment]
I've updated the code to TURN OFF all USB relays on CtrlServer and CtrlClient shutdown. You can pull the latest changes, and after restarting both scripts, the change should take effect.

**Comment by ZishuoYang** [comment]
@yipengsun ok, I will try this today after stopping the burn-in and probably moving the Pi to UPS.

**Comment by yipengsun** [comment]
Given that I haven't heard lots of complaints about Maraton control, i'll close this for now.
