### ISSUE TITLE
Plot the full temperature history 

### ISSUE THREAD

**Issue by ZishuoYang** [umd-lhcb/NeoBurnIn#17]
We want to display the full temperature log, from Wed ~9PM to Fri when we stop the burn-in (~4:30PM).

**Comment by yipengsun** [comment]
@ZishuoYang @Svende Here's the full temperature history plot:
![COMBINED_WIRE](https://user-images.githubusercontent.com/33738176/87250825-27cd6000-c49a-11ea-833c-dc0ed2fb304e.png)

**Comment by yipengsun** [comment]
In case you want to have the raw data: [COMBINED_WIRE.txt](https://github.com/umd-lhcb/NeoBurnIn/files/4908786/COMBINED_WIRE.txt)

Note that this is a `.csv` file, and you need to rename the extension manually. Also, this `.csv` file can be plotted directly in MS Excel.

**Comment by ZishuoYang** [comment]
Looks great. I checked the raw data for the ~50C peak and found only one abnormal value 49.708, so it should be a sensor blip.

**Comment by yipengsun** [comment]
Closed for now. We'll reopen this when we need another plot of full temperature history.
