### ISSUE TITLE
Controlling the PSU (MARATON) with curl doesn't work

### ISSUE THREAD

**Issue by wcparker** [umd-lhcb/NeoBurnIn#20]
I am trying to get the DCB burn in running, for that I need to turn on &off different maraton channels using this command:
curl -X POST http://192.168.1.30:45679/psu/192.168.1.31/<CHANNEL_NUMBER>/off
I can't switch channel 2 off. @yipengsun can you please take a look and help me?

**Comment by yipengsun** [comment]
I just tried again, and the result is `Success`, did it actually work?

**Comment by yipengsun** [comment]
I guess this is a false alarm (?)

Closed for now.
