### ISSUE TITLE
Control server improvements

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/NeoBurnIn#7]
- [x] Add a minimum wait time between consecutive valve opening
- ~~Add a maximum wait time for USB relay control. This would indicates a USB relay failure.~~

**Comment by yipengsun** [comment]
@manuelfs I don't think a maximum wait time is needed. From the controller's perspective, it is just operating an USB relay; We use a Python/Cython wrapper that calls `hid_send_feature_report`, which resides in an external C library. Inspecting the source of that function:

https://github.com/libusb/hidapi/blob/90ddfc61b70cea97dacf33bcd981fb72e27c8da8/libusb/hid.c#L1180-L1208

https://github.com/trezor/cython-hidapi/blob/62b47df8ff46b77e5aa1cb6392132b2d7fb8012e/hid.pyx#L159-L174

That function will timeout after 1000 milliseconds. Should that happen, it will return a non-zero return code.

Based on the observation above, we can just catch non-zero return code emitted by that HID function---that would be a sufficient indicator of a USB relay problem.

By the way, we don't have a way of detecting valve mechanical problems directly.

**Comment by ZishuoYang** [comment]
A max wait time is not for indicating failure of the USB relay. It can indicate failure of the valve/cooling system. For example, when valve should open and cooling water should go through the SBC, but LVRs won't reach the low temp target after 1 hour -- it could be that valve failed to open or that water is not being cooled.

**Comment by yipengsun** [comment]
The situation you described should be covered by over temperature protection. However, if the valve fails to close, then the LVRs will be cooled constantly, making our burn-in less effective. 

But I don't see an easy way to implement such max time (to detect **uninterrupted** cooling): In this case, we need to have a long-running daemon to check temperature must be **above** certain value after a certain period of time.

I'd suggest that we implement over-temperature protection, and ignore the **uninterrupted cooling** protection. The over-temperature protection can be implemented as follows:

1. Monitor the temperature periodically.
2. If the temperature is above over-temperature threshold, shut down PSUs (MARATON) to the LVRs.

**Comment by yipengsun** [comment]
For the minimum wait time, I decide to add a lock (from `asyncio` library) to ensure the valve to not operated repeatedly in a short period of time.

This introduces a setback: The response time is equal to the lock time.

**Comment by yipengsun** [comment]
@bflaggs @manuelfs I implemented a minimum wait time for USB relay. Please test to see if it suits our needs.

**Comment by yipengsun** [comment]
This improved version of minimum wait time doesn't have the setback described in my previous post.

**Comment by yipengsun** [comment]
@manuelfs I believe the minimum wait time is implemented and tested, and the functionality that guarantee that relay operation is successful is implemented by looking at the return code (9 means success, all other values means fail).

I hope the minimum wait time is what you think it is, please ask Ben to show its current behavior, and see if it satisfies our needs (Both Ben and I think it does).
